# Netlify build configuration for a Vite project
[build]
  command = "npm run build"
  publish = "dist"      # The output folder for Vite

# The magic redirect rule for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200